### ISSUE TITLE
False positive Unexpected keyword argument

### ISSUE THREAD

**Issue by edugarcam** [microsoft/vscode-pylint#132] opened 2022-06-24 10:41 UTC
Hi, first of all sorry if I am not making the error report correctly.

Since a week more or less we are having problems with pylint.

If we modify one function adding an additional parameter, calls to this function from other file can not see the new parameter and pylint show the error "Unexpected keyword argument".

Only restarting VSCode the new parameter is saw by pylint.

Thank you!

**Comment by alkatar21** [comment] 2022-06-24 10:50
I can confirm that. I think this has been the case with the extension all along.

A tip as better workaround, open the Command Pallet (`Ctrl + Shift + p`) -> `Pylint: Restart Linter` also works, then only the linter restarts and not everything that has to do with VSCode.

**Comment by karthiknadig** [comment] 2022-06-24 18:04
Pylint might be caching something for faster linting. Having to restart linter each time does not feel right.

/cc @DanielNoord

**Comment by DanielNoord** [comment] 2022-06-24 18:21
`pylint` doesn't cache anything so every run is disconnected from the previous run.

**Comment by karthiknadig** [comment] 2022-06-27 15:48
Duplicate of https://github.com/microsoft/vscode-pylint/issues/129

See discussion here for details https://github.com/microsoft/vscode-pylint/issues/129#issuecomment-1165906018. Since pylint is run in a server like manner there is some caching. This is a side effect of that.

**Closed** 2022-06-27 15:48 UTC
Labels: triage-needed
